
  0%|          | 0/5528 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/minjae/llamarec/LlamaRec/train_ranker.py", line 72, in <module>
    main(args, export_root=None)
  File "/home/minjae/llamarec/LlamaRec/train_ranker.py", line 65, in main
    trainer.train()
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/transformers/trainer.py", line 1556, in train
    return inner_training_loop(
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/transformers/trainer.py", line 1838, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/transformers/trainer.py", line 2693, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/transformers/trainer.py", line 2718, in compute_loss
    outputs = model(**inputs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/minjae/llamarec/LlamaRec/model/llm.py", line 806, in forward
    outputs = self.model(
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/minjae/llamarec/LlamaRec/model/llm.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/minjae/llamarec/LlamaRec/model/llm.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/minjae/llamarec/LlamaRec/model/llm.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minjae/anaconda3/envs/llamarec/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/minjae/llamarec/LlamaRec/model/llm.py", line 330, in forward
    attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 268.00 MiB (GPU 0; 10.75 GiB total capacity; 9.89 GiB already allocated; 80.62 MiB free; 10.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF